version: '3'
networks:
  default:
    external:
      name: temple-webscraper
services:
  app:
    build: .
    ports:
      - '4002:4002'
    restart: always
    volumes:
      - .:/usr/src/app

    command: npm run start:dev